FROM node:22-alpine AS frontend-builder

WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ ./

RUN npm run build


FROM nginx:1.27-alpine

COPY nginx/nginx.conf \
    /etc/nginx/conf.d/default.conf

COPY --from=frontend-builder \
    /frontend/dist \
    /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]